# Generated by Django 5.2.17 on 2026-08-28 07:34

import django.core.validators
from django.db import migrations, models

import profiles.models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_picture_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    profiles.validators.validate_profile_picture_size,
                ],
            ),
        ),
    ]
