# Generated by Django 5.2.17 on 2026-08-29 06:29
# ruff: noqa: E501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quizzes", "0002_question_generation_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("max_players", models.PositiveSmallIntegerField(default=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_contests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contests",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="multiplayer.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "joined_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ContestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("awarded_points", models.PositiveSmallIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_answers",
                        to="quizzes.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contest_selections",
                        to="quizzes.answeroption",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="multiplayer.contestparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ("answered_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="contest",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_players__gte", 2), ("max_players__lte", 100)),
                name="contest_player_limit_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="contestparticipant",
            constraint=models.UniqueConstraint(
                fields=("contest", "user"), name="one_contest_participation_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="contestanswer",
            constraint=models.UniqueConstraint(
                fields=("participant", "question"), name="one_contest_answer_per_question"
            ),
        ),
    ]
