# Generated by Django 5.2.17 on 2026-08-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="generation_attempts",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quiz",
            name="requested_question_count",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation_attempts__gte", 1)),
                name="question_generation_attempts_at_least_one",
            ),
        ),
    ]
