# Generated by Django 5.2.17 on 2026-08-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quizzes", "0002_question_generation_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoloAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=12,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField()),
                ("question_count", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solo_attempts",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solo_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SoloAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("awarded_points", models.PositiveSmallIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solo_answers",
                        to="quizzes.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solo_selections",
                        to="quizzes.answeroption",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="games.soloattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("answered_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="soloattempt",
            index=models.Index(fields=["user", "status"], name="solo_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="soloattempt",
            index=models.Index(fields=["quiz", "started_at"], name="solo_quiz_started_idx"),
        ),
        migrations.AddConstraint(
            model_name="soloattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__lte", models.F("max_score"))),
                name="solo_score_not_above_maximum",
            ),
        ),
        migrations.AddConstraint(
            model_name="soloattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_count__gte", 1)),
                name="solo_question_count_at_least_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="soloanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="one_answer_per_solo_attempt_question"
            ),
        ),
    ]
