# Generated by Django 5.2.17 on 2026-08-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soloattempt",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
